apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: u16
spec:
  type: NodePort     # Use LoadBalancer if cloud
  selector:
    app: nginx
    version: blue
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30101
